#!/bin/bash
# Generated by cc-statusline v1.3.2 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2025-10-02T21:55:42.874Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, session, tokens, burnrate
STATUSLINE_VERSION="1.3.2"

input=$(cat)

# Get the directory where this statusline script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/statusline.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- logging ----
{
  echo "[$TIMESTAMP] Status line triggered (cc-statusline v${STATUSLINE_VERSION})"
  echo "[$TIMESTAMP] Input:"
  if [ "$HAS_JQ" -eq 1 ]; then
    echo "$input" | jq . 2>/dev/null || echo "$input"
    echo "[$TIMESTAMP] Using jq for JSON parsing"
  else
    echo "$input"
    echo "[$TIMESTAMP] WARNING: jq not found, using bash fallback for JSON parsing"
  fi
  echo "---"
} >> "$LOG_FILE" 2>/dev/null

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple  
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- effort level (v2.1.139+: .effort.level in stdin JSON, or $CLAUDE_EFFORT env) ----
# The effort.level enum is low/medium/high/xhigh/max/ultra. Two signals exist and
# they intentionally differ for ultracode: the stdin JSON .effort.level carries the
# STORED level (literally "ultra" for ultracode), while $CLAUDE_EFFORT carries what
# the model actually RECEIVES ("xhigh" for ultracode). The statusline runs as a bash
# subprocess of Claude Code so it inherits $CLAUDE_EFFORT; we prefer the stdin field
# when present (more precise) and fall back to the env var. Models without an effort
# control (e.g. Haiku) omit the field entirely → segment hidden.
effort_level=""
if [ "$HAS_JQ" -eq 1 ]; then
  effort_level=$(echo "$input" | jq -r '.effort.level // .effort // empty' 2>/dev/null)
fi
if [ -z "$effort_level" ] || [ "$effort_level" = "null" ]; then
  effort_level="${CLAUDE_EFFORT:-}"
fi
effort_display=""
case "$effort_level" in
  ultra)                effort_display="ultracode" ;;        # xhigh + dynamic workflow orchestration
  xhigh)                effort_display="xhigh + workflows" ;; # env-side view of ultracode / explicit xhigh
  max)                  effort_display="max" ;;
  high|medium|low|auto) effort_display="$effort_level" ;;
  "")                   effort_display="" ;;
  *)                    effort_display="$effort_level" ;;
esac

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }
# effort color: bright magenta for top-intensity (ultra/xhigh/max), amber for the rest
effort_color() {
  if [ "$use_color" -eq 1 ]; then
    case "$effort_level" in
      ultra|xhigh|max) printf '\033[1;38;5;201m' ;;
      *)               printf '\033[38;5;214m' ;;
    esac
  fi
}

# ---- git ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
fi

# ---- context window calculation ----
context_pct=""
current_usage=""
exceeds_200k=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;37m'; fi; }  # default white

# Extract current_usage from status line input (v2.0.70+)
if [ "$HAS_JQ" -eq 1 ]; then
  current_usage=$(echo "$input" | jq -r '.current_usage // empty' 2>/dev/null)
  exceeds_200k=$(echo "$input" | jq -r '.exceeds_200k_tokens // empty' 2>/dev/null)
else
  current_usage=$(echo "$input" | grep -o '"current_usage"[[:space:]]*:[[:space:]]*[0-9.]*' | sed 's/.*:[[:space:]]*\([0-9.]*\).*/\1/')
  exceeds_200k=$(echo "$input" | grep -o '"exceeds_200k_tokens"[[:space:]]*:[[:space:]]*\(true\|false\)' | sed 's/.*:[[:space:]]*\(true\|false\).*/\1/')
fi

# Use current_usage if available (more accurate from v2.0.70+).
# NOTE: current_usage is percent-of-auto-compact-threshold (160k), not
# percent of model max. It can exceed 100, which is why the clamp is
# required — without it, "100 - 114" emits "-14%" as we hit in 2026-05-20.
if [ -n "$current_usage" ] && [[ "$current_usage" =~ ^[0-9.]+$ ]]; then
  context_used_pct=$(printf '%.0f' "$current_usage")
  context_remaining_pct=$(( 100 - context_used_pct ))
  [ "$context_remaining_pct" -lt 0 ] && context_remaining_pct=0
  [ "$context_remaining_pct" -gt 100 ] && context_remaining_pct=100

  # Set color based on remaining percentage
  if [ "$context_remaining_pct" -le 20 ]; then
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
  elif [ "$context_remaining_pct" -le 40 ]; then
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
  else
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
  fi

  context_pct="${context_remaining_pct}%"
fi

# Determine max context based on model
get_max_context() {
  local model_name="$1"
  case "$model_name" in
    *"Opus 4"*|*"opus 4"*|*"Opus"*|*"opus"*)
      echo "200000"  # 200K for all Opus versions
      ;;
    *"Sonnet 4"*|*"sonnet 4"*|*"Sonnet 3.5"*|*"sonnet 3.5"*|*"Sonnet"*|*"sonnet"*)
      echo "200000"  # 200K for Sonnet 3.5+ and 4.x
      ;;
    *"Haiku 3.5"*|*"haiku 3.5"*|*"Haiku 4"*|*"haiku 4"*|*"Haiku"*|*"haiku"*)
      echo "200000"  # 200K for modern Haiku
      ;;
    *"Claude 3 Haiku"*|*"claude 3 haiku"*)
      echo "100000"  # 100K for original Claude 3 Haiku
      ;;
    *)
      echo "200000"  # Default to 200K
      ;;
  esac
}

if [ -n "$session_id" ] && [ "$HAS_JQ" -eq 1 ]; then
  MAX_CONTEXT=$(get_max_context "$model_name")
  
  # Convert current dir to session file path
  project_dir=$(echo "$current_dir" | sed "s|~|$HOME|g" | sed 's|/|-|g' | sed 's|^-||')
  session_file="$HOME/.claude/projects/-${project_dir}/${session_id}.jsonl"
  
  if [ -f "$session_file" ]; then
    # Get the latest input token count from the session file
    latest_tokens=$(tail -20 "$session_file" | jq -r 'select(.message.usage) | .message.usage | ((.input_tokens // 0) + (.cache_read_input_tokens // 0))' 2>/dev/null | tail -1)
    
    if [ -n "$latest_tokens" ] && [ "$latest_tokens" -gt 0 ]; then
      context_used_pct=$(( latest_tokens * 100 / MAX_CONTEXT ))
      context_remaining_pct=$(( 100 - context_used_pct ))
      # Clamp: cache_read totals can push used past 100% on long sessions
      [ "$context_remaining_pct" -lt 0 ] && context_remaining_pct=0
      [ "$context_remaining_pct" -gt 100 ] && context_remaining_pct=100
      
      # Set color based on remaining percentage
      if [ "$context_remaining_pct" -le 20 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
      elif [ "$context_remaining_pct" -le 40 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
      else
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
      fi
      
      context_pct="${context_remaining_pct}%"
    fi
  fi
fi

# ---- usage colors ----
usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;189m'; fi; }  # lavender
cost_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;222m'; fi; }   # light gold
burn_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;220m'; fi; }   # bright gold
session_color() { 
  rem_pct=$(( 100 - session_pct ))
  if   (( rem_pct <= 10 )); then SCLR='38;5;210'  # light pink
  elif (( rem_pct <= 25 )); then SCLR='38;5;228'  # light yellow  
  else                          SCLR='38;5;194'; fi  # light green
  if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$SCLR"; fi
}

# ---- cost and usage extraction ----
session_txt=""; session_pct=0; session_bar=""
cost_usd=""; cost_per_hour=""; tpm=""; tot_tokens=""

# Extract cost data from Claude Code input
if [ "$HAS_JQ" -eq 1 ]; then
  # Get cost data from Claude Code's input
  cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty' 2>/dev/null)
  total_duration_ms=$(echo "$input" | jq -r '.cost.total_duration_ms // empty' 2>/dev/null)
  
  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    # Convert ms to hours and calculate rate
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi
else
  # Bash fallback for cost extraction
  cost_usd=$(echo "$input" | grep -o '"total_cost_usd"[[:space:]]*:[[:space:]]*[0-9.]*' | sed 's/.*:[[:space:]]*\([0-9.]*\).*/\1/')
  total_duration_ms=$(echo "$input" | grep -o '"total_duration_ms"[[:space:]]*:[[:space:]]*[0-9]*' | sed 's/.*:[[:space:]]*\([0-9]*\).*/\1/')  
  
  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    # Convert ms to hours and calculate rate
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi
fi

# Get token data and session info from ccusage if available
if command -v ccusage >/dev/null 2>&1 && [ "$HAS_JQ" -eq 1 ]; then
  blocks_output=""
  
  # Try ccusage with timeout for token data and session info
  if command -v timeout >/dev/null 2>&1; then
    blocks_output=$(timeout 5s ccusage blocks --json 2>/dev/null)
  elif command -v gtimeout >/dev/null 2>&1; then
    # macOS with coreutils installed
    blocks_output=$(gtimeout 5s ccusage blocks --json 2>/dev/null)
  else
    # No timeout available, run directly (ccusage should be fast)
    blocks_output=$(ccusage blocks --json 2>/dev/null)
  fi
  if [ -n "$blocks_output" ]; then
    active_block=$(echo "$blocks_output" | jq -c '.blocks[] | select(.isActive == true)' 2>/dev/null | head -n1)
    if [ -n "$active_block" ]; then
      # Get token count from ccusage
      tot_tokens=$(echo "$active_block" | jq -r '.totalTokens // empty')
      # Get tokens per minute from ccusage
      tpm=$(echo "$active_block" | jq -r '.burnRate.tokensPerMinute // empty')
      
      # Session time calculation from ccusage
      reset_time_str=$(echo "$active_block" | jq -r '.usageLimitResetTime // .endTime // empty')
      start_time_str=$(echo "$active_block" | jq -r '.startTime // empty')
      
      if [ -n "$reset_time_str" ] && [ -n "$start_time_str" ]; then
        start_sec=$(to_epoch "$start_time_str"); end_sec=$(to_epoch "$reset_time_str"); now_sec=$(date +%s)
        total=$(( end_sec - start_sec )); (( total<1 )) && total=1
        elapsed=$(( now_sec - start_sec )); (( elapsed<0 ))&&elapsed=0; (( elapsed>total ))&&elapsed=$total
        session_pct=$(( elapsed * 100 / total ))
        remaining=$(( end_sec - now_sec )); (( remaining<0 )) && remaining=0
        rh=$(( remaining / 3600 )); rm=$(( (remaining % 3600) / 60 ))
        end_hm=$(fmt_time_hm "$end_sec")
        session_txt="$(printf '%dh %dm until reset at %s (%d%%)' "$rh" "$rm" "$end_hm" "$session_pct")"
        session_bar=$(progress_bar "$session_pct" 10)
      fi
    fi
  fi
fi

# ---- log extracted data ----
{
  echo "[$TIMESTAMP] Extracted: dir=${current_dir:-}, model=${model_name:-}, version=${model_version:-}, git=${git_branch:-}, context=${context_pct:-}, cost=${cost_usd:-}, cost_ph=${cost_per_hour:-}, tokens=${tot_tokens:-}, tpm=${tpm:-}, session_pct=${session_pct:-}"
  if [ "$HAS_JQ" -eq 0 ]; then
    echo "[$TIMESTAMP] Note: Context, tokens, and session info require jq for full functionality"
  fi
} >> "$LOG_FILE" 2>/dev/null

# ---- render statusline ----
# Line 1: Core info (directory, git, model, claude code version, output style)
printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
if [ -n "$git_branch" ]; then
  printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
fi
printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
if [ -n "$effort_display" ]; then
  printf '  ⚡ %s%s%s' "$(effort_color)" "$effort_display" "$(rst)"
fi
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ]; then
  printf '  📟 %sv%s%s' "$(cc_version_color)" "$cc_version" "$(rst)"
fi
if [ -n "$output_style" ] && [ "$output_style" != "null" ]; then
  printf '  🎨 %s%s%s' "$(style_color)" "$output_style" "$(rst)"
fi

# ---- background agent indicator (cached 10s) ----
# Renders an "agent dashboard" segment showing one dot per relevant bg
# session, color-coded by STATE (not role). Idle bg agents are unusual
# in this workflow — agents normally come up, run, and exit — so an
# idle dot is a signal that a session is stale/orphaned and worth
# cleaning up.
#
# Dot conventions:
#   ● green  = running (status=busy)
#   ● white  = idle (status=idle)
#   ● red    = shutting down (status=stopping, or any non-busy/idle —
#              forward-compat if Claude adds intermediate statuses)
#
# Layout:
#   👤 main  bg  ● ● ●  (N running / M active)        — all same state
#   👤 main  bg  ● ● ●  (1 running, 1 stopping, 1 idle) — mixed
#
# Sort order: supervisor → worker → other (role is not color-encoded
# but order is preserved so the leftmost dot is the deepest in the
# launch chain).
#
# Falls back to nothing when there are zero bg sessions in the project.
if [ "$HAS_JQ" -eq 1 ] && command -v claude >/dev/null 2>&1; then
  # Cache is PWD-relative (same as launches_file below) so the statusline
  # and downstream tooling agree on a single per-project state location,
  # regardless of where statusline.sh itself lives.
  bg_cache="$PWD/.claude/state/bg-agents-cache.json"
  bg_cache_age=999
  if [ -f "$bg_cache" ]; then
    bg_cache_age=$(( $(date +%s) - $(stat -f %m "$bg_cache" 2>/dev/null || echo 0) ))
  fi
  if [ "$bg_cache_age" -gt 10 ]; then
    mkdir -p "$PWD/.claude/state" 2>/dev/null
    # Use the extended wrapper so Agent-tool subagents (kind: "subagent") appear
    # alongside `claude agents --json` output (kind: "background" / "interactive").
    # The wrapper degrades gracefully when the script is missing (e.g., on a
    # consumer repo that hasn't synced yet) — fall back to raw `claude agents`.
    _STATUSLINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    _EXT_WRAPPER="$_STATUSLINE_DIR/scripts/claude-agents-extended.sh"
    if [ -x "$_EXT_WRAPPER" ]; then
      "$_EXT_WRAPPER" 2>/dev/null > "$bg_cache.tmp" && mv "$bg_cache.tmp" "$bg_cache" 2>/dev/null
    else
      claude agents --json 2>/dev/null > "$bg_cache.tmp" && mv "$bg_cache.tmp" "$bg_cache" 2>/dev/null
    fi
  fi
  own_sid=""
  if [ -n "${CLAUDE_JOB_DIR:-}" ]; then
    own_sid=$(basename "$CLAUDE_JOB_DIR")
    # pwt-launches.jsonl stores 8-char sid prefixes; the registry's
    # parent_sid field is also 8 chars. Truncate so equality matches.
    # Without this, my_sids seed degenerates to just [own_sid_full]
    # and no parent_sid row ever matches — the entire "mine" set
    # silently collapses to nothing.
    own_sid="${own_sid:0:8}"
  fi

  # Build set of "my-launch" sessionIds from pwt-launches.jsonl (transitive: a sid
  # is mine if it's in the file OR its parent_sid chain reaches a sid that is)
  # AND a role map keyed by sid prefix ("supervisor" | "worker" | absent).
  launches_file="$PWD/.claude/state/pwt-launches.jsonl"
  my_sids_json="[]"
  role_map_json="{}"
  if [ -f "$launches_file" ]; then
    my_sids_json=$(jq -s --arg own "$own_sid" '
      . as $entries
      | ([$own] + [$entries[] | select(.parent_sid == $own) | .sid])
      | unique
      | . as $seed
      | reduce range(0; 4) as $_ (
          $seed;
          . as $cur | . + [$entries[] | select(.parent_sid as $p | $cur | index($p)) | .sid] | unique
        )
    ' "$launches_file" 2>/dev/null || echo "[]")
    role_map_json=$(jq -s '
      map(select(.role) | {key: .sid, value: .role})
      | from_entries
    ' "$launches_file" 2>/dev/null || echo "{}")
  fi

  if [ -f "$bg_cache" ]; then
    # Build the bg-bucket dashboard array (kind: "background"):
    #   [ {role: "supervisor"|"worker"|"other", busy: bool, sid: "abcd1234"}, ... ]
    # Sorted: supervisor first, then worker, then other. Stable within group.
    dashboard_json=$(jq --arg cwd "$PWD" --arg own "$own_sid" \
                        --argjson mine "$my_sids_json" \
                        --argjson roles "$role_map_json" '
      [.[]
        | select(.kind == "background")
        | select(.cwd == $cwd or (.cwd | startswith($cwd + "/")))
        | select(.sessionId[:8] != $own)
        | . as $a
        | {
            sid: $a.sessionId[:8],
            status: ($a.status // "idle"),
            busy: ($a.status == "busy"),
            role: (
              if ($mine | index($a.sessionId[:8])) then
                ($roles[$a.sessionId[:8]] // "worker")
              else
                "other"
              end
            )
          }
      ]
      | sort_by(
          if .role == "supervisor" then 0
          elif .role == "worker"   then 1
          else 2 end
        )
    ' "$bg_cache" 2>/dev/null || echo "[]")

    # Build the sub-bucket dashboard array (kind: "subagent" — emitted by
    # claude-agents-extended.sh from ~/.claude/projects/*/subagents/agent-*.jsonl).
    # Subagents are always "mine" (sidechain children of the current session),
    # so the role-filter isn't applied here; the cwd filter is the only gate.
    sub_dashboard_json=$(jq --arg cwd "$PWD" '
      [.[]
        | select(.kind == "subagent")
        | select(.cwd == $cwd or (.cwd | startswith($cwd + "/")))
        | {
            sid:    ((.agentId // .sessionId // "")[:8]),
            status: (.status // "busy"),
            busy:   ((.status // "busy") == "busy"),
            role:   "worker"
          }
      ]
    ' "$bg_cache" 2>/dev/null || echo "[]")

    # Build the wf-bucket dashboard array (kind: "workflow" — dynamic-Workflow
    # lens-agents from subagents/workflows/wf_<run>/). Like subagents these are
    # always "mine" (children of THIS session's `Workflow` tool call), so only the
    # cwd gate applies. Previously uncaptured entirely: a running workflow showed
    # no dots, so the line read as "idle" while a fan-out was actively churning.
    wf_dashboard_json=$(jq --arg cwd "$PWD" '
      [.[]
        | select(.kind == "workflow")
        | select(.cwd == $cwd or (.cwd | startswith($cwd + "/")))
        | {
            sid:    ((.agentId // .sessionId // "")[:8]),
            status: (.status // "busy"),
            busy:   ((.status // "busy") == "busy"),
            role:   "worker",
            run:    (.workflowRun // "")
          }
      ]
    ' "$bg_cache" 2>/dev/null || echo "[]")

    bg_total=$(echo "$dashboard_json"     | jq 'length' 2>/dev/null || echo 0)
    sub_total=$(echo "$sub_dashboard_json" | jq 'length' 2>/dev/null || echo 0)
    wf_total=$(echo "$wf_dashboard_json"  | jq 'length' 2>/dev/null || echo 0)
    total_count=$(( bg_total + sub_total + wf_total ))
    mine_count=$(echo "$dashboard_json" | jq '[.[] | select(.role != "other")] | length' 2>/dev/null || echo 0)
    # Subagents and workflow lens-agents are always "mine" by definition.
    mine_count=$(( mine_count + sub_total + wf_total ))

    # Phase label decision:
    #   - mine_count > 0           → "🚀 Agents Running"   (supervisor chain alive)
    #   - mine_count == 0 AND unread summary file exists → "✅ Agents Completed"
    #   - mine_count == 0 AND other_count > 0 → fall back to old "👤 main 👥 N other"
    #   - all zero                  → emit nothing
    summaries_count=0
    if [ -d "$PWD/.claude/state" ]; then
      summaries_count=$(find "$PWD/.claude/state" -maxdepth 1 -name 'pwt-completion-summary-*.md' 2>/dev/null | wc -l | tr -d ' ')
    fi

    # Render one bucket: dots + trailing count summary.
    # Args: <label> <bucket-json>
    _render_bucket() {
      local label="$1" bucket="$2"
      local b_total b_run b_idle b_stop
      b_total=$(echo "$bucket" | jq 'length' 2>/dev/null || echo 0)
      [ "$b_total" = "0" ] && return
      b_run=$(echo  "$bucket" | jq '[.[] | select(.status == "busy")] | length' 2>/dev/null || echo 0)
      b_idle=$(echo "$bucket" | jq '[.[] | select(.status == "idle")] | length' 2>/dev/null || echo 0)
      b_stop=$(echo "$bucket" | jq '[.[] | select(.status != "busy" and .status != "idle")] | length' 2>/dev/null || echo 0)

      printf '  %s%s%s  ' "$(C '38;5;245')" "$label" "$(rst)"

      # One dot per agent, color = state.
      echo "$bucket" | jq -r '.[] | .status' 2>/dev/null | while read -r status; do
        case "$status" in
          busy) color="38;5;46"  ;; # bright green = running
          idle) color="38;5;255" ;; # bright white = idle (unusual — stale/orphan)
          *)    color="38;5;203" ;; # coral red    = stopping / unknown
        esac
        printf '%s●%s ' "$(C "$color")" "$(rst)"
      done

      local label_color="$(C '38;5;245')" label_rst="$(rst)"
      if   [ "$b_run"  = "$b_total" ]; then
        printf '%s(%s running)%s' "$label_color" "$b_total" "$label_rst"
      elif [ "$b_idle" = "$b_total" ]; then
        printf '%s(%s idle)%s' "$label_color" "$b_total" "$label_rst"
      elif [ "$b_stop" = "$b_total" ]; then
        printf '%s(%s stopping)%s' "$label_color" "$b_total" "$label_rst"
      else
        local parts=""
        [ "$b_run"  != "0" ] && parts="${parts}, ${b_run} running"
        [ "$b_stop" != "0" ] && parts="${parts}, ${b_stop} stopping"
        [ "$b_idle" != "0" ] && parts="${parts}, ${b_idle} idle"
        parts="${parts#, }"
        printf '%s(%s)%s' "$label_color" "$parts" "$label_rst"
      fi
    }

    # Emit the agents indicator on its own line (line 1 already has cwd +
    # branch + model + git status — adding agents on the same line clips on
    # narrow terminals). The leading \n breaks to a new line; 2-space indent
    # visually subordinates it to the main statusline.
    if [ "$total_count" != "0" ]; then
      printf '\n  👤 %smain%s' "$(C '38;5;117')" "$(rst)"
      _render_bucket "bg"  "$dashboard_json"
      _render_bucket "sub" "$sub_dashboard_json"
      _render_bucket "wf"  "$wf_dashboard_json"
    elif [ "$summaries_count" != "0" ]; then
      printf '\n  ✅ %sAgents Completed%s — summary in chat ↓' "$(C '38;5;46')" "$(rst)"
    fi
  fi
fi

# Line 2: Claude plan usage (5-hour + 7-day windows) + session time
#
# Data source: Anthropic's /api/oauth/usage endpoint — the exact data the
# interactive `/usage` slash command shows. We don't compute it ourselves;
# we just call the same API Claude Code calls and surface the result.
#
# Context-remaining was removed: it lied after auto-compact, /compact is
# already prompted by Claude Code itself when imminent, and `/context`
# is one keystroke when the user wants the visual grid view.
line2=""
PLAN_USAGE_HELPER="$PWD/.claude/scripts/plan-usage.sh"
if [ -x "$PLAN_USAGE_HELPER" ] && [ "$HAS_JQ" -eq 1 ]; then
  plan_json=$("$PLAN_USAGE_HELPER" 2>/dev/null)
  if [ -n "$plan_json" ] && [ "$plan_json" != "{}" ]; then
    five_hr=$(echo "$plan_json" | jq -r '.five_hour.utilization // empty' 2>/dev/null)
    seven_d=$(echo "$plan_json" | jq -r '.seven_day.utilization // empty' 2>/dev/null)
    five_hr_reset=$(echo "$plan_json" | jq -r '.five_hour.resets_at // empty' 2>/dev/null)

    # Format reset time as LOCAL HH:MM. The API returns ISO-8601 in UTC;
    # we use python3 because macOS `date -j` doesn't handle timezone-aware
    # ISO parsing cleanly. Falls back to empty on any error.
    reset_local=""
    if [ -n "$five_hr_reset" ]; then
      reset_local=$(RESET_TS="$five_hr_reset" python3 -c '
import os
from datetime import datetime
try:
    ts = os.environ.get("RESET_TS", "")
    # Tolerate trailing Z or +HH:MM, plus fractional seconds
    ts_clean = ts.replace("Z", "+00:00")
    dt = datetime.fromisoformat(ts_clean)
    # astimezone() with no arg converts UTC-aware dt → local tz
    print(dt.astimezone().strftime("%H:%M"))
except Exception:
    pass
' 2>/dev/null)
    fi

    # Color by utilization (5-hour is what matters most for active-session pressure)
    five_color() { :; }
    if [ -n "$five_hr" ]; then
      five_int=$(printf '%.0f' "$five_hr" 2>/dev/null || echo 0)
      if [ "$five_int" -ge 80 ]; then
        five_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
      elif [ "$five_int" -ge 50 ]; then
        five_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
      else
        five_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
      fi
    fi

    # Build the segment: "📊 Plan: 5h 2% (resets 18:00) · 7d 11% · 👤 email (tier)"
    if [ -n "$five_hr" ]; then
      five_hr_fmt=$(printf '%.0f' "$five_hr" 2>/dev/null || echo "$five_hr")
      line2="📊 $(C '38;5;117')Plan:$(rst) $(five_color)5h ${five_hr_fmt}%$(rst)"
      [ -n "$reset_local" ] && line2="$line2 $(C '38;5;245')(resets ${reset_local})$(rst)"
      if [ -n "$seven_d" ]; then
        seven_d_fmt=$(printf '%.0f' "$seven_d" 2>/dev/null || echo "$seven_d")
        line2="$line2 $(C '38;5;245')·$(rst) $(C '38;5;117')7d ${seven_d_fmt}%$(rst)"
      fi
    fi
  fi
fi

# Append account identity to line2 so multi-account users can tell at a glance
# which Claude account is logged in. Reads ~/.claude.json — local, no network.
ACCOUNT_INFO_HELPER="$PWD/.claude/scripts/account-info.sh"
if [ -x "$ACCOUNT_INFO_HELPER" ] && [ "$HAS_JQ" -eq 1 ]; then
  acct_json=$("$ACCOUNT_INFO_HELPER" 2>/dev/null)
  if [ -n "$acct_json" ] && [ "$acct_json" != "{}" ]; then
    acct_email=$(echo "$acct_json" | jq -r '.email // empty' 2>/dev/null)
    acct_tier=$(echo "$acct_json" | jq -r '.tier // empty' 2>/dev/null)
    if [ -n "$acct_email" ]; then
      acct_seg="$(C '38;5;117')👤 ${acct_email}$(rst)"
      [ -n "$acct_tier" ] && acct_seg="$acct_seg $(C '38;5;245')(${acct_tier})$(rst)"
      if [ -n "$line2" ]; then
        line2="$line2 $(C '38;5;245')·$(rst) $acct_seg"
      else
        line2="$acct_seg"
      fi
    fi
  fi
fi

# Session time still useful as a context-window proxy (long session → /compact incoming)
if [ -n "$session_txt" ]; then
  if [ -n "$line2" ]; then
    line2="$line2  ⌛ $(session_color)${session_txt}$(rst) $(session_color)[${session_bar}]$(rst)"
  else
    line2="⌛ $(session_color)${session_txt}$(rst) $(session_color)[${session_bar}]$(rst)"
  fi
fi

# Line 3: Usage analytics (Max-subscription-friendly)
#
# Dollar cost / $/h dropped: this repo's user is on Claude Max only —
# no API spend ever. The displayed $ was always theatrical, and for
# multi-day sessions it grew unboundedly without conveying any signal.
#
# What's kept: total tokens and tpm from `ccusage blocks`. Those map
# to the 5-hour billing window which IS the real Max-subscription
# constraint — they tell the user when they're burning quota fast
# enough to risk hitting their 5-hour cap mid-run.
line3=""
if [ -n "$tot_tokens" ] && [[ "$tot_tokens" =~ ^[0-9]+$ ]]; then
  if [ -n "$tpm" ] && [[ "$tpm" =~ ^[0-9.]+$ ]]; then
    tpm_formatted=$(printf '%.0f' "$tpm")
    line3="📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
  else
    line3="📊 $(usage_color)${tot_tokens} tok$(rst)"
  fi
fi

# Line 4: /usage today breakdown — top skill/subagent/MCP by token attribution
# from local session transcripts (~/.claude/projects/**/*.jsonl modified today).
# Mirrors Boris's /usage interactive output: percentages can overlap because a
# turn may invoke multiple tool categories.
line4=""
USAGE_BREAKDOWN_HELPER="$PWD/.claude/scripts/usage-breakdown.sh"
if [ -x "$USAGE_BREAKDOWN_HELPER" ] && [ "$HAS_JQ" -eq 1 ]; then
  ub_json=$("$USAGE_BREAKDOWN_HELPER" 2>/dev/null)
  if [ -n "$ub_json" ] && [ "$ub_json" != "{}" ]; then
    # Build "🎯 Today: Skill /X N% · Agent Y N% · MCP Z N%" segment.
    # Each row pulls the top-1 entry; if no entries, the segment is skipped.
    parts=""
    top_skill=$(echo "$ub_json" | jq -r '.skills[0] | "\(.name) \(.pct)"' 2>/dev/null)
    if [ -n "$top_skill" ] && [ "$top_skill" != "null null" ]; then
      sk_name=$(echo "$top_skill" | awk '{print $1}')
      sk_pct=$(echo "$top_skill" | awk '{print $2}')
      parts="$(C '38;5;117')Skill$(rst) $(C '38;5;215')/${sk_name}$(rst) ${sk_pct}%"
    fi
    top_agent=$(echo "$ub_json" | jq -r '.subagents[0] | "\(.name) \(.pct)"' 2>/dev/null)
    if [ -n "$top_agent" ] && [ "$top_agent" != "null null" ]; then
      ag_name=$(echo "$top_agent" | awk '{print $1}')
      ag_pct=$(echo "$top_agent" | awk '{print $2}')
      [ -n "$parts" ] && parts="$parts $(C '38;5;245')·$(rst) "
      parts="$parts$(C '38;5;117')Agent$(rst) $(C '38;5;215')${ag_name}$(rst) ${ag_pct}%"
    fi
    top_mcp=$(echo "$ub_json" | jq -r '.mcp[0] | "\(.name) \(.pct)"' 2>/dev/null)
    if [ -n "$top_mcp" ] && [ "$top_mcp" != "null null" ]; then
      mc_name=$(echo "$top_mcp" | awk '{print $1}')
      mc_pct=$(echo "$top_mcp" | awk '{print $2}')
      [ -n "$parts" ] && parts="$parts $(C '38;5;245')·$(rst) "
      parts="$parts$(C '38;5;117')MCP$(rst) $(C '38;5;215')${mc_name}$(rst) ${mc_pct}%"
    fi
    [ -n "$parts" ] && line4="🎯 $(C '38;5;117')Today:$(rst) $parts"
  fi
fi

# Print lines
if [ -n "$line2" ]; then
  printf '\n%s' "$line2"
fi
if [ -n "$line3" ]; then
  printf '\n%s' "$line3"
fi
if [ -n "$line4" ]; then
  printf '\n%s' "$line4"
fi
printf '\n'
