#!/bin/bash
# Generated by cc-statusline v1.3.2 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2025-10-02T21:55:42.874Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, session, tokens, burnrate
STATUSLINE_VERSION="1.3.2"

input=$(cat)

# Get the directory where this statusline script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/statusline.log"

# Project root for every state/helper path below: $PWD walked up to the git
# root via `git rev-parse --show-cdup` (a worktree resolves to ITS OWN root),
# falling back to $PWD when the cwd is not inside a git repo (sandboxed tests,
# plain directories). The LOGICAL path is kept on purpose (`pwd -L`, not
# --show-toplevel): the bg-agents cache stores each session's cwd as a logical
# string and the dashboard filters compare prefixes, so a symlinked cwd (macOS
# /var → /private/var) must resolve the same way here. Bare $PWD scattered
# nested .claude/state/ dirs into apps/*, tests/* whenever a session sat in a
# subdirectory — one such stale file false-failed a consumer's pre-push gate
# (2026-09-02).
if _cdup="$(git rev-parse --show-cdup 2>/dev/null)"; then
  PROJECT_ROOT="$(cd "${_cdup:-.}" 2>/dev/null && pwd -L)"
fi
[ -n "${PROJECT_ROOT:-}" ] || PROJECT_ROOT="$PWD"
unset _cdup

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- lean mode for /plan-w-team pipeline sessions (F1, 2026-08-19 incident) ----
# A pipeline worker/supervisor re-renders this line on EVERY tool-call turn, and
# the two helpers that parse the transcript corpus (ccusage, usage-breakdown)
# cost more the longer the run gets. That is a positive feedback loop: longer
# run → bigger transcripts → costlier helper → slower host → longer run. It
# measured load 24–27 on 12 cores over hours and starved the run's own lane.
# pwt-goal.sh exports PWT_LEAN_STATUSLINE=1 into every bg spawn, and the
# supervisor protocol sets it for the duration of supervision, so those sessions
# render the cheap segments only. Nobody is watching a bg worker's status line.
# Kill switch: PWT_DISABLE_LEAN_STATUSLINE=1 restores the full line everywhere.
# Scope note: this skips the TRANSCRIPT-HISTORY parsers specifically. The
# bg-agents segment stays — it is O(sessions), already cached and detached, and
# it is the one segment that is actually about the pipeline.
PWT_LEAN=0
if [ "${PWT_LEAN_STATUSLINE:-0}" = "1" ] && [ "${PWT_DISABLE_LEAN_STATUSLINE:-0}" != "1" ]; then
  PWT_LEAN=1
fi

# ---- logging (opt-in) ----
# LOCAL PATCH on cc-statusline-generated code — regenerating via cc-statusline
# would clobber it. The generated block appended the full session-input JSON
# (via a spawned jq) to statusline.log on EVERY render, unbounded — measured
# multi-GB logs per repo fleet-wide (2026-07-19). Debug logging is now opt-in
# via STATUSLINE_DEBUG=1; default is zero log writes and zero jq/date spawns.
# Even with debug on, the log self-caps: past 10 MB it is truncated (this is
# debug scaffolding, not an archive).
if [ "${STATUSLINE_DEBUG:-0}" = "1" ]; then
  TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
  if [ -f "$LOG_FILE" ]; then
    log_bytes=$(wc -c < "$LOG_FILE" 2>/dev/null | tr -d '[:space:]')
    if [ "${log_bytes:-0}" -gt 10485760 ]; then
      : > "$LOG_FILE"
    fi
  fi
  {
    echo "[$TIMESTAMP] Status line triggered (cc-statusline v${STATUSLINE_VERSION})"
    echo "[$TIMESTAMP] Input:"
    if [ "$HAS_JQ" -eq 1 ]; then
      echo "$input" | jq . 2>/dev/null || echo "$input"
      echo "[$TIMESTAMP] Using jq for JSON parsing"
    else
      echo "$input"
      echo "[$TIMESTAMP] WARNING: jq not found, using bash fallback for JSON parsing"
    fi
    echo "---"
  } >> "$LOG_FILE" 2>/dev/null
fi

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple  
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

# Local wall-clock time in 12-hour US form ("3:00pm", "11:45am") — every
# user-facing time on the line goes through here (plan resets, ccusage block end).
# Set STATUSLINE_TIME_24H=1 for "15:00". GNU and BSD date both honour %I/%p; the
# leading zero is stripped in shell so no non-portable %-I is needed.
fmt_time_hm() {
  local epoch="$1" out
  if [ "${STATUSLINE_TIME_24H:-0}" = "1" ]; then
    if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
    return 0
  fi
  if date -r 0 +%s >/dev/null 2>&1; then out=$(date -r "$epoch" +"%I:%M%p"); else out=$(date -d "@$epoch" +"%I:%M%p"); fi
  out="${out#0}"
  printf '%s' "$out" | tr 'APM' 'apm'
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- effort level (v2.1.139+: .effort.level in stdin JSON, or $CLAUDE_EFFORT env) ----
# The effort.level enum is low/medium/high/xhigh/max/ultra. Two signals exist and
# they intentionally differ for ultracode: the stdin JSON .effort.level carries the
# STORED level (literally "ultra" for ultracode), while $CLAUDE_EFFORT carries what
# the model actually RECEIVES ("xhigh" for ultracode). The statusline runs as a bash
# subprocess of Claude Code so it inherits $CLAUDE_EFFORT; we prefer the stdin field
# when present (more precise) and fall back to the env var. Models without an effort
# control (e.g. Haiku) omit the field entirely → segment hidden.
effort_level=""
if [ "$HAS_JQ" -eq 1 ]; then
  effort_level=$(echo "$input" | jq -r '.effort.level // .effort // empty' 2>/dev/null)
fi
if [ -z "$effort_level" ] || [ "$effort_level" = "null" ]; then
  effort_level="${CLAUDE_EFFORT:-}"
fi
effort_display=""
case "$effort_level" in
  ultra)                effort_display="ultracode" ;;        # xhigh + dynamic workflow orchestration
  xhigh)                effort_display="xhigh + workflows" ;; # env-side view of ultracode / explicit xhigh
  max)                  effort_display="max" ;;
  high|medium|low|auto) effort_display="$effort_level" ;;
  "")                   effort_display="" ;;
  *)                    effort_display="$effort_level" ;;
esac

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }
# effort color: bright magenta for top-intensity (ultra/xhigh/max), amber for the rest
effort_color() {
  if [ "$use_color" -eq 1 ]; then
    case "$effort_level" in
      ultra|xhigh|max) printf '\033[1;38;5;201m' ;;
      *)               printf '\033[38;5;214m' ;;
    esac
  fi
}

# ---- git ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
fi

# ---- context window calculation ----
context_pct=""
current_usage=""
exceeds_200k=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;37m'; fi; }  # default white

# Extract current_usage from status line input (v2.0.70+)
if [ "$HAS_JQ" -eq 1 ]; then
  current_usage=$(echo "$input" | jq -r '.current_usage // empty' 2>/dev/null)
  exceeds_200k=$(echo "$input" | jq -r '.exceeds_200k_tokens // empty' 2>/dev/null)
else
  current_usage=$(echo "$input" | grep -o '"current_usage"[[:space:]]*:[[:space:]]*[0-9.]*' | sed 's/.*:[[:space:]]*\([0-9.]*\).*/\1/')
  exceeds_200k=$(echo "$input" | grep -o '"exceeds_200k_tokens"[[:space:]]*:[[:space:]]*\(true\|false\)' | sed 's/.*:[[:space:]]*\(true\|false\).*/\1/')
fi

# Use current_usage if available (more accurate from v2.0.70+).
# NOTE: current_usage is percent-of-auto-compact-threshold (160k), not
# percent of model max. It can exceed 100, which is why the clamp is
# required — without it, "100 - 114" emits "-14%" as we hit in 2026-05-20.
if [ -n "$current_usage" ] && [[ "$current_usage" =~ ^[0-9.]+$ ]]; then
  context_used_pct=$(printf '%.0f' "$current_usage")
  context_remaining_pct=$(( 100 - context_used_pct ))
  [ "$context_remaining_pct" -lt 0 ] && context_remaining_pct=0
  [ "$context_remaining_pct" -gt 100 ] && context_remaining_pct=100

  # Set color based on remaining percentage
  if [ "$context_remaining_pct" -le 20 ]; then
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
  elif [ "$context_remaining_pct" -le 40 ]; then
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
  else
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
  fi

  context_pct="${context_remaining_pct}%"
fi

# Determine max context based on model
get_max_context() {
  local model_name="$1"
  case "$model_name" in
    *"Opus 4"*|*"opus 4"*|*"Opus"*|*"opus"*)
      echo "200000"  # 200K for all Opus versions
      ;;
    *"Sonnet 4"*|*"sonnet 4"*|*"Sonnet 3.5"*|*"sonnet 3.5"*|*"Sonnet"*|*"sonnet"*)
      echo "200000"  # 200K for Sonnet 3.5+ and 4.x
      ;;
    *"Haiku 3.5"*|*"haiku 3.5"*|*"Haiku 4"*|*"haiku 4"*|*"Haiku"*|*"haiku"*)
      echo "200000"  # 200K for modern Haiku
      ;;
    *"Claude 3 Haiku"*|*"claude 3 haiku"*)
      echo "100000"  # 100K for original Claude 3 Haiku
      ;;
    *)
      echo "200000"  # Default to 200K
      ;;
  esac
}

if [ -n "$session_id" ] && [ "$HAS_JQ" -eq 1 ]; then
  MAX_CONTEXT=$(get_max_context "$model_name")
  
  # Convert current dir to session file path
  project_dir=$(echo "$current_dir" | sed "s|~|$HOME|g" | sed 's|/|-|g' | sed 's|^-||')
  session_file="$HOME/.claude/projects/-${project_dir}/${session_id}.jsonl"
  
  if [ -f "$session_file" ]; then
    # Get the latest input token count from the session file
    latest_tokens=$(tail -20 "$session_file" | jq -r 'select(.message.usage) | .message.usage | ((.input_tokens // 0) + (.cache_read_input_tokens // 0))' 2>/dev/null | tail -1)
    
    if [ -n "$latest_tokens" ] && [ "$latest_tokens" -gt 0 ]; then
      context_used_pct=$(( latest_tokens * 100 / MAX_CONTEXT ))
      context_remaining_pct=$(( 100 - context_used_pct ))
      # Clamp: cache_read totals can push used past 100% on long sessions
      [ "$context_remaining_pct" -lt 0 ] && context_remaining_pct=0
      [ "$context_remaining_pct" -gt 100 ] && context_remaining_pct=100
      
      # Set color based on remaining percentage
      if [ "$context_remaining_pct" -le 20 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
      elif [ "$context_remaining_pct" -le 40 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
      else
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
      fi
      
      context_pct="${context_remaining_pct}%"
    fi
  fi
fi

# ---- usage colors ----
usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;189m'; fi; }  # lavender
cost_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;222m'; fi; }   # light gold
burn_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;220m'; fi; }   # bright gold
session_color() { 
  rem_pct=$(( 100 - session_pct ))
  if   (( rem_pct <= 10 )); then SCLR='38;5;210'  # light pink
  elif (( rem_pct <= 25 )); then SCLR='38;5;228'  # light yellow  
  else                          SCLR='38;5;194'; fi  # light green
  if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$SCLR"; fi
}

# ---- cost and usage extraction ----
session_txt=""; session_pct=0; session_bar=""
cost_usd=""; cost_per_hour=""; tpm=""; tot_tokens=""

# Extract cost data from Claude Code input
if [ "$HAS_JQ" -eq 1 ]; then
  # Get cost data from Claude Code's input
  cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty' 2>/dev/null)
  total_duration_ms=$(echo "$input" | jq -r '.cost.total_duration_ms // empty' 2>/dev/null)
  
  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    # Convert ms to hours and calculate rate
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi
else
  # Bash fallback for cost extraction
  cost_usd=$(echo "$input" | grep -o '"total_cost_usd"[[:space:]]*:[[:space:]]*[0-9.]*' | sed 's/.*:[[:space:]]*\([0-9.]*\).*/\1/')
  total_duration_ms=$(echo "$input" | grep -o '"total_duration_ms"[[:space:]]*:[[:space:]]*[0-9]*' | sed 's/.*:[[:space:]]*\([0-9]*\).*/\1/')  
  
  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    # Convert ms to hours and calculate rate
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi
fi

# Get token data and session info via the bounded ccusage helper.
#
# The previous inline block probed `timeout`, then `gtimeout`, then — on a host
# with NEITHER, which is stock macOS — ran `ccusage blocks --json` UNBOUNDED,
# with a comment ("ccusage should be fast") standing in for the bound. There was
# also no cache and no singleton, so every render stacked another multi-second,
# multi-core process. That was root cause RC1 of the 2026-08-19 incident.
#
# ccusage-blocks.sh now owns the bound (a real timeout binary is REQUIRED — no
# binary, no call), the 60s cache and the mkdir singleton, and it honors the lean
# gate. Same helper shape as plan-usage.sh / usage-breakdown.sh / account-info.sh.
# A repo that has not synced the helper simply renders no token segment — the
# unbounded path is gone, not relocated.
CCUSAGE_HELPER="$PROJECT_ROOT/.claude/scripts/ccusage-blocks.sh"
if [ "$PWT_LEAN" -eq 0 ] && [ -x "$CCUSAGE_HELPER" ] && [ "$HAS_JQ" -eq 1 ]; then
  blocks_output=$("$CCUSAGE_HELPER" 2>/dev/null)
  if [ -n "$blocks_output" ]; then
    active_block=$(echo "$blocks_output" | jq -c '.blocks[] | select(.isActive == true)' 2>/dev/null | head -n1)
    if [ -n "$active_block" ]; then
      # Get token count from ccusage
      tot_tokens=$(echo "$active_block" | jq -r '.totalTokens // empty')
      # Get tokens per minute from ccusage
      tpm=$(echo "$active_block" | jq -r '.burnRate.tokensPerMinute // empty')
      
      # Session time calculation from ccusage
      reset_time_str=$(echo "$active_block" | jq -r '.usageLimitResetTime // .endTime // empty')
      start_time_str=$(echo "$active_block" | jq -r '.startTime // empty')
      
      if [ -n "$reset_time_str" ] && [ -n "$start_time_str" ]; then
        start_sec=$(to_epoch "$start_time_str"); end_sec=$(to_epoch "$reset_time_str"); now_sec=$(date +%s)
        total=$(( end_sec - start_sec )); (( total<1 )) && total=1
        elapsed=$(( now_sec - start_sec )); (( elapsed<0 ))&&elapsed=0; (( elapsed>total ))&&elapsed=$total
        session_pct=$(( elapsed * 100 / total ))
        remaining=$(( end_sec - now_sec )); (( remaining<0 )) && remaining=0
        rh=$(( remaining / 3600 )); rm=$(( (remaining % 3600) / 60 ))
        end_hm=$(fmt_time_hm "$end_sec")
        session_txt="$(printf '%dh %dm until reset at %s (%d%%)' "$rh" "$rm" "$end_hm" "$session_pct")"
        session_bar=$(progress_bar "$session_pct" 10)
      fi
    fi
  fi
fi

# ---- log extracted data (opt-in — see STATUSLINE_DEBUG patch note above) ----
if [ "${STATUSLINE_DEBUG:-0}" = "1" ]; then
  {
    echo "[$TIMESTAMP] Extracted: dir=${current_dir:-}, model=${model_name:-}, version=${model_version:-}, git=${git_branch:-}, context=${context_pct:-}, cost=${cost_usd:-}, cost_ph=${cost_per_hour:-}, tokens=${tot_tokens:-}, tpm=${tpm:-}, session_pct=${session_pct:-}"
    if [ "$HAS_JQ" -eq 0 ]; then
      echo "[$TIMESTAMP] Note: Context, tokens, and session info require jq for full functionality"
    fi
  } >> "$LOG_FILE" 2>/dev/null
fi

# ---- render statusline ----
# Line 1: Core info (directory, git, model, claude code version, output style)
printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
if [ -n "$git_branch" ]; then
  printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
fi
printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
if [ -n "$effort_display" ]; then
  printf '  ⚡ %s%s%s' "$(effort_color)" "$effort_display" "$(rst)"
fi
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ]; then
  printf '  📟 %sv%s%s' "$(cc_version_color)" "$cc_version" "$(rst)"
fi
if [ -n "$output_style" ] && [ "$output_style" != "null" ]; then
  printf '  🎨 %s%s%s' "$(style_color)" "$output_style" "$(rst)"
fi

# ---- background agent indicator (cached 10s) ----
# Renders an "agent dashboard" segment showing one dot per relevant bg
# session, color-coded by STATE (not role). Idle bg agents are unusual
# in this workflow — agents normally come up, run, and exit — so an
# idle dot is a signal that a session is stale/orphaned and worth
# cleaning up.
#
# Dot conventions:
#   ● green  = running (status=busy)
#   ● white  = idle (status=idle)
#   ● red    = shutting down (status=stopping, or any non-busy/idle —
#              forward-compat if Claude adds intermediate statuses)
#
# Layout:
#   👤 main  bg  ● ● ●  (N running / M active)        — all same state
#   👤 main  bg  ● ● ●  (1 running, 1 stopping, 1 idle) — mixed
#
# Sort order: supervisor → worker → other (role is not color-encoded
# but order is preserved so the leftmost dot is the deepest in the
# launch chain).
#
# Falls back to nothing when there are zero bg sessions in the project.
if [ "$HAS_JQ" -eq 1 ] && command -v claude >/dev/null 2>&1; then
  # Cache lives under PROJECT_ROOT (same as launches_file below) so the
  # statusline and downstream tooling agree on a single per-project state
  # location, regardless of where statusline.sh itself lives or which
  # subdirectory the session's cwd happens to be.
  bg_cache="$PROJECT_ROOT/.claude/state/bg-agents-cache.json"
  bg_cache_age=999
  if [ -f "$bg_cache" ]; then
    bg_cache_age=$(( $(date +%s) - $(stat -f %m "$bg_cache" 2>/dev/null || echo 0) ))
  fi
  if [ "$bg_cache_age" -gt 10 ]; then
    mkdir -p "$PROJECT_ROOT/.claude/state" 2>/dev/null
    # Use the extended wrapper so Agent-tool subagents (kind: "subagent") appear
    # alongside `claude agents --json` output (kind: "background" / "interactive").
    # The wrapper degrades gracefully when the script is missing (e.g., on a
    # consumer repo that hasn't synced yet) — fall back to raw `claude agents`.
    _STATUSLINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    _EXT_WRAPPER="$_STATUSLINE_DIR/scripts/claude-agents-extended.sh"
    # Stale-while-revalidate: refresh in a DETACHED background process and
    # render THIS pass from the existing cache. Claude Code cancels an
    # in-flight statusline command whenever a new update trigger fires
    # (refreshInterval or any conversation event), so a synchronous refresh
    # that outlives the trigger gap is killed mid-run: the cache never
    # commits, every render restarts cold, and everything printed after this
    # section (plan / usage / today lines) never appears. Busy sessions hit
    # that loop permanently. Detached (own process group via set -m) the
    # refresh survives the cancellation and a later pass picks up the result.
    #
    # Stampede guard: a marker file skips re-spawning while a refresh is in
    # flight; a marker older than 60s is treated as orphaned and reclaimed.
    # Worst case on the claim race is one duplicate refresher — harmless,
    # both commit atomically via mv of unique tmp files.
    _bg_marker="$bg_cache.refreshing"
    _marker_age=999
    if [ -f "$_bg_marker" ]; then
      _marker_age=$(( $(date +%s) - $(stat -f %m "$_bg_marker" 2>/dev/null || echo 0) ))
    fi
    if [ "$_marker_age" -gt 60 ]; then
      : > "$_bg_marker" 2>/dev/null
      rm -f "$bg_cache.tmp" 2>/dev/null  # reap pre-fix orphan (sync refresh killed mid-write)
      _refresh_via=""
      [ -x "$_EXT_WRAPPER" ] && _refresh_via="$_EXT_WRAPPER"
      (
        set -m 2>/dev/null
        nohup bash -c '
          cache="$1"; wrapper="$2"; out="$cache.tmp.$$"
          if [ -n "$wrapper" ]; then
            "$wrapper" > "$out" 2>/dev/null
          else
            claude agents --json > "$out" 2>/dev/null
          fi && [ -s "$out" ] && mv "$out" "$cache" 2>/dev/null
          rm -f "$out" "$cache.refreshing" 2>/dev/null
        ' _ "$bg_cache" "$_refresh_via" </dev/null >/dev/null 2>&1 &
      ) 2>/dev/null
    fi
  fi
  own_sid=""
  if [ -n "${CLAUDE_JOB_DIR:-}" ]; then
    own_sid=$(basename "$CLAUDE_JOB_DIR")
    # pwt-launches.jsonl stores 8-char sid prefixes; the registry's
    # parent_sid field is also 8 chars. Truncate so equality matches.
    # Without this, my_sids seed degenerates to just [own_sid_full]
    # and no parent_sid row ever matches — the entire "mine" set
    # silently collapses to nothing.
    own_sid="${own_sid:0:8}"
  fi
  # Interactive panes have no CLAUDE_JOB_DIR — fall back to the session_id
  # Claude Code passes on statusline stdin. This is what makes the agents
  # line PANE-SCOPED: with own_sid known, each pane shows only its own
  # agent tree (2026-08-06 operator directive — multiple panes on one repo
  # previously all showed the union of the repo's sessions).
  if [ -z "$own_sid" ] && [ "$HAS_JQ" -eq 1 ]; then
    own_sid=$(echo "$input" | jq -r '.session_id // empty' 2>/dev/null)
    own_sid="${own_sid:0:8}"
  fi

  # Build set of "my-launch" sessionIds from pwt-launches.jsonl (transitive: a sid
  # is mine if it's in the file OR its parent_sid chain reaches a sid that is)
  # AND a role map keyed by sid prefix ("supervisor" | "worker" | absent).
  launches_file="$PROJECT_ROOT/.claude/state/pwt-launches.jsonl"
  my_sids_json="[]"
  role_map_json="{}"
  if [ -f "$launches_file" ]; then
    my_sids_json=$(jq -s --arg own "$own_sid" '
      . as $entries
      | ([$own] + [$entries[] | select(.parent_sid == $own) | .sid])
      | unique
      | . as $seed
      | reduce range(0; 4) as $_ (
          $seed;
          . as $cur | . + [$entries[] | select(.parent_sid as $p | $cur | index($p)) | .sid] | unique
        )
    ' "$launches_file" 2>/dev/null || echo "[]")
    role_map_json=$(jq -s '
      map(select(.role) | {key: .sid, value: .role})
      | from_entries
    ' "$launches_file" 2>/dev/null || echo "{}")
  fi

  if [ -f "$bg_cache" ]; then
    # Build the bg-bucket dashboard array (kind: "background"):
    #   [ {role: "supervisor"|"worker"|"other", busy: bool, sid: "abcd1234"}, ... ]
    # Sorted: supervisor first, then worker, then other. Stable within group.
    dashboard_json=$(jq --arg cwd "$PROJECT_ROOT" --arg own "$own_sid" \
                        --argjson mine "$my_sids_json" \
                        --argjson roles "$role_map_json" '
      [.[]
        | select(.kind == "background")
        | select(.cwd == $cwd or (.cwd | startswith($cwd + "/")))
        | select(.sessionId[:8] != $own)
        | . as $a
        | {
            sid: $a.sessionId[:8],
            status: ($a.status // "idle"),
            busy: ($a.status == "busy"),
            role: (
              if ($mine | index($a.sessionId[:8])) then
                ($roles[$a.sessionId[:8]] // "worker")
              else
                "other"
              end
            )
          }
      ]
      | sort_by(
          if .role == "supervisor" then 0
          elif .role == "worker"   then 1
          else 2 end
        )
    ' "$bg_cache" 2>/dev/null || echo "[]")

    # Build the sub-bucket dashboard array (kind: "subagent" — emitted by
    # claude-agents-extended.sh from ~/.claude/projects/*/subagents/agent-*.jsonl).
    # PANE-SCOPED (2026-08-06): a subagent is "mine" only when its
    # parentSessionId is THIS session (or a session this one spawned, per the
    # launches registry). The old assumption "subagents are always mine" broke
    # whenever two sessions shared a repo — every pane showed the union.
    # Empty own_sid (no session_id on stdin, old harness) keeps legacy behavior.
    sub_dashboard_json=$(jq --arg cwd "$PROJECT_ROOT" --arg own "$own_sid" --argjson mine "$my_sids_json" '
      [.[]
        | select(.kind == "subagent")
        | select(.cwd == $cwd or (.cwd | startswith($cwd + "/")))
        | ((.parentSessionId // "")[:8]) as $p
        | {
            sid:    ((.agentId // .sessionId // "")[:8]),
            status: (.status // "busy"),
            busy:   ((.status // "busy") == "busy"),
            role:   "worker",
            mine:   ($own == "" or $p == $own or (($mine | index($p)) != null))
          }
      ]
    ' "$bg_cache" 2>/dev/null || echo "[]")

    # Build the wf-bucket dashboard array (kind: "workflow" — dynamic-Workflow
    # lens-agents from subagents/workflows/wf_<run>/). Like subagents these are
    # always "mine" (children of THIS session's `Workflow` tool call), so only the
    # cwd gate applies. Previously uncaptured entirely: a running workflow showed
    # no dots, so the line read as "idle" while a fan-out was actively churning.
    wf_dashboard_json=$(jq --arg cwd "$PROJECT_ROOT" --arg own "$own_sid" --argjson mine "$my_sids_json" '
      [.[]
        | select(.kind == "workflow")
        | select(.cwd == $cwd or (.cwd | startswith($cwd + "/")))
        | ((.parentSessionId // "")[:8]) as $p
        | {
            sid:    ((.agentId // .sessionId // "")[:8]),
            status: (.status // "busy"),
            busy:   ((.status // "busy") == "busy"),
            role:   "worker",
            run:    (.workflowRun // ""),
            mine:   ($own == "" or $p == $own or (($mine | index($p)) != null))
          }
      ]
    ' "$bg_cache" 2>/dev/null || echo "[]")

    # PANE-SCOPED SPLIT (2026-08-06): dots render only THIS pane's agent tree;
    # everything else in the repo collapses to a muted "+N other" count.
    bg_mine_json=$(echo "$dashboard_json"      | jq '[.[] | select(.role != "other")]' 2>/dev/null || echo "[]")
    sub_mine_json=$(echo "$sub_dashboard_json" | jq '[.[] | select(.mine)]' 2>/dev/null || echo "[]")
    wf_mine_json=$(echo "$wf_dashboard_json"   | jq '[.[] | select(.mine)]' 2>/dev/null || echo "[]")
    bg_total=$(echo "$bg_mine_json"   | jq 'length' 2>/dev/null || echo 0)
    sub_total=$(echo "$sub_mine_json" | jq 'length' 2>/dev/null || echo 0)
    wf_total=$(echo "$wf_mine_json"   | jq 'length' 2>/dev/null || echo 0)
    other_count=$(( \
      $(echo "$dashboard_json"      | jq '[.[] | select(.role == "other")] | length' 2>/dev/null || echo 0) + \
      $(echo "$sub_dashboard_json"  | jq '[.[] | select(.mine | not)] | length' 2>/dev/null || echo 0) + \
      $(echo "$wf_dashboard_json"   | jq '[.[] | select(.mine | not)] | length' 2>/dev/null || echo 0) ))
    total_count=$(( bg_total + sub_total + wf_total ))
    mine_count=$total_count

    # Phase label decision:
    #   - mine_count > 0           → "🚀 Agents Running"   (supervisor chain alive)
    #   - mine_count == 0 AND unread summary file exists → "✅ Agents Completed"
    #   - mine_count == 0 AND other_count > 0 → fall back to old "👤 main 👥 N other"
    #   - all zero                  → emit nothing
    summaries_count=0
    if [ -d "$PROJECT_ROOT/.claude/state" ]; then
      summaries_count=$(find "$PROJECT_ROOT/.claude/state" -maxdepth 1 -name 'pwt-completion-summary-*.md' 2>/dev/null | wc -l | tr -d ' ')
    fi

    # Render one bucket: dots + trailing count summary.
    # Args: <label> <bucket-json>
    _render_bucket() {
      local label="$1" bucket="$2"
      local b_total b_run b_idle b_stop
      b_total=$(echo "$bucket" | jq 'length' 2>/dev/null || echo 0)
      [ "$b_total" = "0" ] && return
      b_run=$(echo  "$bucket" | jq '[.[] | select(.status == "busy")] | length' 2>/dev/null || echo 0)
      b_idle=$(echo "$bucket" | jq '[.[] | select(.status == "idle")] | length' 2>/dev/null || echo 0)
      b_stop=$(echo "$bucket" | jq '[.[] | select(.status != "busy" and .status != "idle")] | length' 2>/dev/null || echo 0)

      printf '  %s%s%s  ' "$(C '38;5;245')" "$label" "$(rst)"

      # One dot per agent, color = state.
      echo "$bucket" | jq -r '.[] | .status' 2>/dev/null | while read -r status; do
        case "$status" in
          busy) color="38;5;46"  ;; # bright green = running
          idle) color="38;5;255" ;; # bright white = idle (unusual — stale/orphan)
          *)    color="38;5;203" ;; # coral red    = stopping / unknown
        esac
        printf '%s●%s ' "$(C "$color")" "$(rst)"
      done

      local label_color="$(C '38;5;245')" label_rst="$(rst)"
      if   [ "$b_run"  = "$b_total" ]; then
        printf '%s(%s running)%s' "$label_color" "$b_total" "$label_rst"
      elif [ "$b_idle" = "$b_total" ]; then
        printf '%s(%s idle)%s' "$label_color" "$b_total" "$label_rst"
      elif [ "$b_stop" = "$b_total" ]; then
        printf '%s(%s stopping)%s' "$label_color" "$b_total" "$label_rst"
      else
        local parts=""
        [ "$b_run"  != "0" ] && parts="${parts}, ${b_run} running"
        [ "$b_stop" != "0" ] && parts="${parts}, ${b_stop} stopping"
        [ "$b_idle" != "0" ] && parts="${parts}, ${b_idle} idle"
        parts="${parts#, }"
        printf '%s(%s)%s' "$label_color" "$parts" "$label_rst"
      fi
    }

    # Emit the agents indicator on its own line (line 1 already has cwd +
    # branch + model + git status — adding agents on the same line clips on
    # narrow terminals). The leading \n breaks to a new line; 2-space indent
    # visually subordinates it to the main statusline.
    if [ "$total_count" != "0" ]; then
      printf '\n  👤 %smain%s' "$(C '38;5;117')" "$(rst)"
      _render_bucket "bg"  "$bg_mine_json"
      _render_bucket "sub" "$sub_mine_json"
      _render_bucket "wf"  "$wf_mine_json"
      [ "$other_count" != "0" ] && printf '  %s+%s other in repo%s' "$(C '38;5;240')" "$other_count" "$(rst)"
    elif [ "$other_count" != "0" ]; then
      # Nothing of this pane's is running, but other sessions in this repo
      # have live agents — show a muted count, never their dots.
      printf '\n  👤 %smain%s  %s👥 %s agent(s) in repo — other sessions%s' "$(C '38;5;117')" "$(rst)" "$(C '38;5;240')" "$other_count" "$(rst)"
    elif [ "$summaries_count" != "0" ]; then
      printf '\n  ✅ %sAgents Completed%s — summary in chat ↓' "$(C '38;5;46')" "$(rst)"
    fi
  fi
fi

# Usage heat tiers — ONE definition for every segment that colors by plan
# utilization (the 📊 Plan 5h number and the 👉 next / ⚠ switch advisory), so a
# nudge can never sit green beside a peach or red plan number (2026-09-01).
# Thresholds match the producer's default switch hint (PWT_ACCT_SWITCH_HINT_PCT=80).
usage_tier() {  # <pct-int> → hot | warm | cool
  if [ "${1:-0}" -ge 80 ] 2>/dev/null; then echo hot
  elif [ "${1:-0}" -ge 50 ] 2>/dev/null; then echo warm
  else echo cool; fi
}
tier_color() {  # <tier> → SGR params for C()
  case "$1" in
    hot)  echo '38;5;203' ;;  # coral red
    warm) echo '38;5;215' ;;  # peach
    *)    echo '38;5;158' ;;  # mint green
  esac
}

# Line 2: Claude plan usage (5h + 7d + model-scoped weekly windows) + session time
#
# Data: the `rate_limits` object Claude Code passes on stdin (this session's
# last API response) reconciled with the account-keyed /api/oauth/usage cache
# that plan-usage.sh refreshes off the render path — the exact data the
# interactive `/usage` slash command shows. Full contract:
# docs/operations/statusline-usage-reporting.md
#
# Context-remaining was removed: it lied after auto-compact, /compact is
# already prompted by Claude Code itself when imminent, and `/context`
# is one keystroke when the user wants the visual grid view.
line2=""
# ── Plan usage: two sources, reconciled ─────────────────────────────────────
# (a) stdin `rate_limits` (Claude Code ≥ 2.1.251): the 5h/7d gauge from THIS
#     session's most recent API response. Zero cost and exactly the identity this
#     pane bills to — but it only moves when THIS pane makes a request, so an idle
#     pane's copy goes stale while other panes on the same account keep burning.
# (b) plan-usage.sh: the machine-wide, ACCOUNT-KEYED /api/oauth/usage cache,
#     refreshed every 60 s by a DETACHED bounded singleton — never in this render
#     path. Claude Code cancels an in-flight status-line command when the next
#     trigger fires; a synchronous fetch here was killed under load, so the line
#     froze at "5h 87%" while the account was at 100% and every session on it was
#     being rejected (2026-09-02). The helper also carries what stdin does not:
#     the model-scoped weekly limits (the Fable bucket has been the BINDING limit
#     at 61% while 5h read 7%), which limit is_active (▸), locked_reason, the
#     sample's age and a burn-rate ETA.
# Usage only rises inside a window, so for 5h/7d the truest current value is the
# MAX of the readings whose resets_at has not passed. Every number is colored by
# its own heat tier (usage_tier); an ETA under 15 min is hot regardless of the
# percentage, because "87%" and "100% in six minutes" are the same fact.
PLAN_USAGE_HELPER="$PROJECT_ROOT/.claude/scripts/plan-usage.sh"
plan_json=""
if [ -x "$PLAN_USAGE_HELPER" ] && [ "$HAS_JQ" -eq 1 ]; then
  # Signed with this pane's session_id so a failure backoff gates only its writer (2.38.1).
  plan_json=$(PLAN_USAGE_WRITER="${session_id:-}" "$PLAN_USAGE_HELPER" 2>/dev/null)
  [ "$plan_json" = "{}" ] && plan_json=""
fi
plan_tier=cool      # hottest tier across every limit — the advisory inherits it
plan_limited=0
five_hr=""; seven_d=""
tier_rank() { case "$1" in hot) echo 2 ;; warm) echo 1 ;; *) echo 0 ;; esac; }
fmt_dur() {  # seconds → 45s | 6m | 1h12m
  local s="${1:-0}"
  case "$s" in ''|*[!0-9]*) s=0 ;; esac
  if [ "$s" -ge 3600 ]; then printf '%dh%02dm' $(( s / 3600 )) $(( (s % 3600) / 60 ))
  elif [ "$s" -ge 60 ]; then printf '%dm' $(( s / 60 ))
  else printf '%ds' "$s"; fi
}
# lim_seg <label> <pct> <eta_s> <locked_reason> <severity> <is_active 0|1>
# Sets LIM_OUT (the colored segment) and bubbles the heat into plan_tier. Not
# called in a $(…) so the globals survive.
lim_seg() {
  local label="$1" pct="$2" eta="$3" lock="$4" sev="$5" active="$6" pi tier mark="" etxt=""
  pi=$(printf '%.0f' "$pct" 2>/dev/null) || pi=0
  case "$pi" in ''|*[!0-9]*) pi=0 ;; esac
  tier=$(usage_tier "$pi")
  # The API's own severity (enum not published beyond "normal"): a non-normal
  # reading can only raise the tier, never lower it.
  case "$sev" in ''|normal) ;; warning) [ "$tier" = cool ] && tier=warm ;; *) tier=hot ;; esac
  case "$eta" in ''|*[!0-9]*) eta="" ;; esac
  if [ -n "$eta" ]; then
    if [ "$eta" -lt 900 ]; then tier=hot
    elif [ "$eta" -lt 2700 ] && [ "$tier" = cool ]; then tier=warm; fi
    [ "$eta" -lt 5400 ] && etxt=" →100% in $(fmt_dur "$eta")"
  fi
  [ "$active" = "1" ] && mark="▸"
  if [ -n "$lock" ] || [ "$pi" -ge 100 ]; then
    tier=hot; plan_limited=1
    LIM_OUT="$(C "$(tier_color hot)")${mark}${label} ⛔ LIMITED$(rst)"
  else
    LIM_OUT="$(C "$(tier_color "$tier")")${mark}${label} ${pi}%${etxt}$(rst)"
  fi
  [ "$(tier_rank "$tier")" -gt "$(tier_rank "$plan_tier")" ] && plan_tier="$tier"
  return 0
}
pick_max() {  # <a> <b> → the larger numeric reading; empty-safe
  local a="$1" b="$2" ai bi
  [ -n "$a" ] || { printf '%s' "$b"; return 0; }
  [ -n "$b" ] || { printf '%s' "$a"; return 0; }
  ai=$(printf '%.0f' "$a" 2>/dev/null) || ai=0; bi=$(printf '%.0f' "$b" 2>/dev/null) || bi=0
  if [ "${ai:-0}" -ge "${bi:-0}" ] 2>/dev/null; then printf '%s' "$a"; else printf '%s' "$b"; fi
}
if [ "$HAS_JQ" -eq 1 ]; then
  now_s=$(date +%s)
  # (a) stdin gauge: used_percentage + resets_at (epoch s), each window optional.
  sd_five=""; sd_five_reset=""; sd_seven=""; sd_seven_reset=""
  sd_line=$(printf '%s' "$input" | jq -r '[(.rate_limits.five_hour.used_percentage // ""), (.rate_limits.five_hour.resets_at // ""), (.rate_limits.seven_day.used_percentage // ""), (.rate_limits.seven_day.resets_at // "")] | map(tostring) | join("|")' 2>/dev/null)
  if [ -n "$sd_line" ]; then
    sd_five="${sd_line%%|*}"; _r="${sd_line#*|}"; sd_five_reset="${_r%%|*}"; _r="${_r#*|}"; sd_seven="${_r%%|*}"; sd_seven_reset="${_r#*|}"
    unset _r
  fi
  # (b) helper sample — one jq, one field per line (empty lines are empty fields).
  h_five=""; h_seven=""; h_five_reset=""; h_seven_reset=""; h_five_lock=""; h_seven_lock=""
  h_fetched=""; h_stale_max=""; h_ttl=""; h_five_eta=""; h_seven_eta=""; h_active=""; h_five_sev=""; h_seven_sev=""; h_login=""
  if [ -n "$plan_json" ]; then
    pf=$(printf '%s' "$plan_json" | jq -r '
      def ep: if . == null or . == "" then "" else (tostring | sub("\\.[0-9]+"; "") | sub("\\+00:00$"; "Z") | (try fromdateiso8601 catch "") | tostring) end;
      def n: if . == null then "" else tostring end;
      (.five_hour.utilization | n), (.seven_day.utilization | n),
      (.five_hour.resets_at | ep), (.seven_day.resets_at | ep),
      (.five_hour.locked_reason | n), (.seven_day.locked_reason | n),
      (._meta.fetched_at | n), (._meta.stale_max_s | n), (._meta.ttl_s | n),
      (._meta.rates.five_hour.eta_s | n), (._meta.rates.seven_day.eta_s | n),
      ([.limits[]? | select(.is_active == true) | .kind] | first // ""),
      ([.limits[]? | select(.kind == "session") | .severity] | first // ""),
      ([.limits[]? | select(.kind == "weekly_all") | .severity] | first // ""),
      (._meta.account_email | n)
    ' 2>/dev/null)
    pf_i=0
    while IFS= read -r pf_l; do
      case $pf_i in
        0) h_five="$pf_l" ;; 1) h_seven="$pf_l" ;; 2) h_five_reset="$pf_l" ;; 3) h_seven_reset="$pf_l" ;;
        4) h_five_lock="$pf_l" ;; 5) h_seven_lock="$pf_l" ;; 6) h_fetched="$pf_l" ;; 7) h_stale_max="$pf_l" ;;
        8) h_ttl="$pf_l" ;; 9) h_five_eta="$pf_l" ;; 10) h_seven_eta="$pf_l" ;; 11) h_active="$pf_l" ;;
        12) h_five_sev="$pf_l" ;; 13) h_seven_sev="$pf_l" ;; 14) h_login="$pf_l" ;;
      esac
      pf_i=$(( pf_i + 1 ))
    done <<< "$pf"
    # A reading from a window that has already reset describes the PREVIOUS
    # window — drop it rather than show a high number that is no longer true.
    case "$h_five_reset" in *[!0-9]*|'') ;; *) [ "$h_five_reset" -le "$now_s" ] && { h_five=""; h_five_reset=""; h_five_lock=""; h_five_eta=""; } ;; esac
    case "$h_seven_reset" in *[!0-9]*|'') ;; *) [ "$h_seven_reset" -le "$now_s" ] && { h_seven=""; h_seven_reset=""; h_seven_lock=""; h_seven_eta=""; } ;; esac
  fi
  case "$sd_five_reset" in *[!0-9]*|'') ;; *) [ "$sd_five_reset" -le "$now_s" ] && { sd_five=""; sd_five_reset=""; } ;; esac
  case "$sd_seven_reset" in *[!0-9]*|'') ;; *) [ "$sd_seven_reset" -le "$now_s" ] && { sd_seven=""; sd_seven_reset=""; } ;; esac
  # Login tag (2.37.4): the reset-time identity below cannot tell accounts apart
  # whose windows COINCIDE — four of the five accounts reset 2:59pm on 2026-09-02
  # and a pane whose last response came from a 103% account rendered ⛔ LIMITED on
  # the current login at 80%. stdin is this session's last response, so the payload
  # is tagged with the login it was FIRST seen under (one tiny file per session,
  # machine-local); an unchanged payload after the login moved on is the previous
  # account's gauge and is dropped. A new payload re-tags under the current login.
  # No session_id, or no login in the sample ⇒ the 2.37.1 behaviour alone.
  if [ -n "${session_id:-}" ] && [ -n "$h_login" ] && [ -n "$sd_line" ] && [ "$sd_line" != "|||" ]; then
    sd_tag_dir="${PLAN_USAGE_STDIN_TAG_DIR:-$HOME/.config/claude-pattern/stdin-tags}"
    sd_tag_f="$sd_tag_dir/${session_id}.tag"
    sd_owner=""
    if [ -f "$sd_tag_f" ] && [ "$(sed -n 1p "$sd_tag_f" 2>/dev/null)" = "$sd_line" ]; then
      sd_owner=$(sed -n 2p "$sd_tag_f" 2>/dev/null)
    else
      mkdir -p "$sd_tag_dir" 2>/dev/null
      printf '%s\n%s\n' "$sd_line" "$h_login" > "$sd_tag_f.$$" 2>/dev/null && mv -f "$sd_tag_f.$$" "$sd_tag_f" 2>/dev/null
      find "$sd_tag_dir" -name '*.tag' -mtime +7 -delete 2>/dev/null
      sd_owner="$h_login"
    fi
    if [ -n "$sd_owner" ] && [ "$sd_owner" != "$h_login" ]; then
      sd_five=""; sd_five_reset=""; sd_seven=""; sd_seven_reset=""
    fi
  fi
  # Identity (2.37.1): stdin is THIS session's LAST response, so after a /login it
  # still carries the PREVIOUS account's gauge until this pane makes a request —
  # MAX then rendered king's 94% with lazio's reset time as one line (2026-09-02).
  # The helper sample is keyed to the CURRENT login, so a stdin reading counts only
  # when its window matches the helper's (resets_at within 120 s); a KNOWN mismatch
  # is another account or an older window and is dropped. Unknown resets keep MAX.
  same_window() {  # <helper-reset> <stdin-reset> → 0 unless both known and apart
    local d
    case "$1" in ''|*[!0-9]*) return 0 ;; esac
    case "$2" in ''|*[!0-9]*) return 0 ;; esac
    d=$(( $1 - $2 )); [ "$d" -lt 0 ] && d=$(( 0 - d ))
    [ "$d" -le 120 ]
  }
  if [ -n "$h_five" ] && [ -n "$sd_five" ] && ! same_window "$h_five_reset" "$sd_five_reset"; then sd_five=""; sd_five_reset=""; fi
  if [ -n "$h_seven" ] && [ -n "$sd_seven" ] && ! same_window "$h_seven_reset" "$sd_seven_reset"; then sd_seven=""; sd_seven_reset=""; fi

  five_hr=$(pick_max "$h_five" "$sd_five")
  seven_d=$(pick_max "$h_seven" "$sd_seven")
  five_reset_ep="${h_five_reset:-$sd_five_reset}"
  five_active=0; seven_active=0
  case "$h_active" in session) five_active=1 ;; weekly_all) seven_active=1 ;; esac

  if [ -n "$five_hr" ]; then
    lim_seg "5h" "$five_hr" "$h_five_eta" "$h_five_lock" "$h_five_sev" "$five_active"
    line2="📊 $(C '38;5;117')Plan:$(rst) $LIM_OUT"
    case "$five_reset_ep" in ''|*[!0-9]*) ;; *) line2="$line2 $(C '38;5;245')(resets $(fmt_time_hm "$five_reset_ep"))$(rst)" ;; esac
  fi
  if [ -n "$seven_d" ]; then
    lim_seg "7d" "$seven_d" "$h_seven_eta" "$h_seven_lock" "$h_seven_sev" "$seven_active"
    if [ -n "$line2" ]; then line2="$line2 $(C '38;5;245')·$(rst) $LIM_OUT"; else line2="📊 $(C '38;5;117')Plan:$(rst) $LIM_OUT"; fi
  fi
  # Model-scoped weekly buckets (e.g. "Fable 61%") — a separate limit that can be
  # the binding one; stdin never carries it, only the helper does.
  if [ -n "$plan_json" ]; then
    sc_lines=$(printf '%s' "$plan_json" | jq -r '. as $d | .limits[]? | select(.kind == "weekly_scoped") | (((.scope.model.display_name) // "?") as $n | [$n, ((.percent // "") | tostring), (if .is_active == true then "1" else "0" end), (.severity // ""), (($d._meta.rates.scoped[$n].eta_s // "") | tostring)] | join("|"))' 2>/dev/null)
    while IFS='|' read -r sc_name sc_pct sc_active sc_sev sc_eta; do
      [ -n "$sc_name" ] && [ -n "$sc_pct" ] || continue
      lim_seg "$sc_name" "$sc_pct" "$sc_eta" "" "$sc_sev" "$sc_active"
      if [ -n "$line2" ]; then line2="$line2 $(C '38;5;245')·$(rst) $LIM_OUT"; else line2="📊 $(C '38;5;117')Plan:$(rst) $LIM_OUT"; fi
    done <<< "$sc_lines"
  fi
  # Sample age. Absent for a legacy helper (no _meta). Quiet under 2×TTL; a grey
  # ⟳ once the refresher is late; a loud STALE past stale_max — red when stdin
  # holds no reading of its own, peach when this pane's own gauge still moves.
  case "$h_fetched" in ''|*[!0-9]*) ;; *)
    plan_age=$(( now_s - h_fetched )); [ "$plan_age" -lt 0 ] && plan_age=0
    case "$h_stale_max" in ''|*[!0-9]*) h_stale_max=900 ;; esac
    case "$h_ttl" in ''|*[!0-9]*) h_ttl=60 ;; esac
    if [ -n "$line2" ]; then
      if [ "$plan_age" -ge "$h_stale_max" ]; then
        stale_tier=hot; [ -n "$sd_five" ] && stale_tier=warm
        line2="$line2 $(C "$(tier_color "$stale_tier")")⚠ STALE $(fmt_dur "$plan_age")$(rst)"
      elif [ "$plan_age" -ge $(( h_ttl * 2 > 420 ? h_ttl * 2 : 420 )) ]; then   # the endpoint serves a new sample every ~5 min: quiet under 7
        line2="$line2 $(C '38;5;245')⟳ $(fmt_dur "$plan_age")$(rst)"
      fi
    fi ;;
  esac
fi

# Append account identity to line2 so multi-account users can tell at a glance
# which Claude account is logged in. Reads ~/.claude.json — local, no network.
ACCOUNT_INFO_HELPER="$PROJECT_ROOT/.claude/scripts/account-info.sh"
if [ -x "$ACCOUNT_INFO_HELPER" ] && [ "$HAS_JQ" -eq 1 ]; then
  acct_json=$("$ACCOUNT_INFO_HELPER" 2>/dev/null)
  if [ -n "$acct_json" ] && [ "$acct_json" != "{}" ]; then
    acct_email=$(echo "$acct_json" | jq -r '.email // empty' 2>/dev/null)
    acct_tier=$(echo "$acct_json" | jq -r '.tier // empty' 2>/dev/null)
    if [ -n "$acct_email" ]; then
      acct_seg="$(C '38;5;117')👤 ${acct_email}$(rst)"
      [ -n "$acct_tier" ] && acct_seg="$acct_seg $(C '38;5;245')(${acct_tier})$(rst)"
      if [ -n "$line2" ]; then
        line2="$line2 $(C '38;5;245')·$(rst) $acct_seg"
      else
        line2="$acct_seg"
      fi
    fi
  fi
fi

# Account rotation advisory: when a registered account has more headroom than the
# one this machine is logged in as, nudge toward it. `👉 next: <email>` normally;
# `⚠ switch → <email>` once the current login gets hot. The segment names the
# account by its FULL EMAIL (`best_email`), falling back to the registry label only
# when the advisory carries no email: labels are operator-chosen stems that collide
# in practice (two accounts on one domain both read as "<company>"), and `/login`
# asks for an email, so the email is the only unambiguous handle (2026-09-01). The
# switch is MANUAL (`/login`) — interactive Claude Code can't be account-switched by
# an env token (2026-08-31). Its COLOR follows the same heat tiers as the 📊 Plan
# 5h number beside it (usage_tier), so the two can never disagree side by side.
# Local-cached + bounded + fail-open (no segment) via
# account-advice.sh; skipped on lean/pipeline statuslines to keep supervising
# renders cheap.
ACCOUNT_ADVICE_HELPER="$PROJECT_ROOT/.claude/scripts/account-advice.sh"
if [ "$PWT_LEAN" -eq 0 ] && [ -x "$ACCOUNT_ADVICE_HELPER" ] && [ "$HAS_JQ" -eq 1 ] && [ -n "$line2" ]; then
  advice_json=$("$ACCOUNT_ADVICE_HELPER" "${acct_email:-}" 2>/dev/null)
  if [ -n "$advice_json" ] && [ "$advice_json" != "{}" ]; then
    adv_switch=$(echo "$advice_json" | jq -r '.switch // false' 2>/dev/null)
    if [ "$adv_switch" = "true" ]; then
      adv_best=$(echo "$advice_json" | jq -r '.best // empty' 2>/dev/null)
      adv_best_email=$(echo "$advice_json" | jq -r '.best_email // empty' 2>/dev/null)
      adv_b5=$(echo "$advice_json" | jq -r '.best_5h // empty' 2>/dev/null)
      adv_b7=$(echo "$advice_json" | jq -r '.best_7d // empty' 2>/dev/null)
      adv_hot=$(echo "$advice_json" | jq -r '.current_hot // false' 2>/dev/null)
      # Email first; label is the fallback so an advisory without an email (older
      # accounts CLI, a registry row missing its email) still renders something.
      adv_who="${adv_best_email:-$adv_best}"
      if [ -n "$adv_who" ]; then
        adv_pct=""
        if [ -n "$adv_b5" ] && [ -n "$adv_b7" ]; then
          adv_b5f=$(printf '%.0f' "$adv_b5" 2>/dev/null || echo "$adv_b5")
          adv_b7f=$(printf '%.0f' "$adv_b7" 2>/dev/null || echo "$adv_b7")
          adv_pct=" (${adv_b5f}/${adv_b7f}%)"
        fi
        # Heat: the SAME tiers as the 📊 Plan 5h number beside it (≥80 hot → red
        # `⚠ switch →`, ≥50 warm → peach, else cool), evaluated over the hottest
        # reading we hold — the plan segment's own 5h AND 7d (the numbers the
        # operator is looking at, fresh from /api/oauth/usage every render) plus the
        # advisory's cached current_5h/7d (a second probe with its own TTL that can
        # lag either way). The producer's `current_hot` still forces hot. Before this
        # the nudge sat green beside a peach `5h 79%` and read as "nothing to do"
        # (2026-09-01).
        adv_c5=$(echo "$advice_json" | jq -r '.current_5h // empty' 2>/dev/null)
        adv_c7=$(echo "$advice_json" | jq -r '.current_7d // empty' 2>/dev/null)
        adv_heat=0
        for adv_v in "${five_hr:-}" "${seven_d:-}" "$adv_c5" "$adv_c7"; do
          [ -n "$adv_v" ] || continue
          adv_vi=$(printf '%.0f' "$adv_v" 2>/dev/null) || continue
          [ "$adv_vi" -gt "$adv_heat" ] 2>/dev/null && adv_heat=$adv_vi
        done
        adv_tier=$(usage_tier "$adv_heat")
        [ "$adv_hot" = "true" ] && adv_tier=hot
        # …and never cooler than the plan segment itself, which also folds in the
        # model-scoped limits, the API severity and the burn-rate ETA.
        [ "$(tier_rank "${plan_tier:-cool}")" -gt "$(tier_rank "$adv_tier")" ] && adv_tier="${plan_tier:-cool}"
        case "$adv_tier" in
          hot)  line2="$line2 $(C '38;5;245')·$(rst) $(C "$(tier_color hot)")⚠ switch → ${adv_who}${adv_pct}$(rst)" ;;
          warm) line2="$line2 $(C '38;5;245')·$(rst) $(C "$(tier_color warm)")👉 next: ${adv_who}${adv_pct}$(rst)" ;;
          # cool keeps the advisory's muted green: an idle nudge stays quieter than
          # the plan number it sits beside.
          *)    line2="$line2 $(C '38;5;245')·$(rst) $(C '38;5;108')👉 next: ${adv_who}${adv_pct}$(rst)" ;;
        esac
      fi
    fi
  fi
fi

# Session time still useful as a context-window proxy (long session → /compact incoming)
if [ -n "$session_txt" ]; then
  if [ -n "$line2" ]; then
    line2="$line2  ⌛ $(session_color)${session_txt}$(rst) $(session_color)[${session_bar}]$(rst)"
  else
    line2="⌛ $(session_color)${session_txt}$(rst) $(session_color)[${session_bar}]$(rst)"
  fi
fi

# Line 3: Usage analytics (Max-subscription-friendly)
#
# Dollar cost / $/h dropped: this repo's user is on Claude Max only —
# no API spend ever. The displayed $ was always theatrical, and for
# multi-day sessions it grew unboundedly without conveying any signal.
#
# What's kept: total tokens and tpm from `ccusage blocks`. Those map
# to the 5-hour billing window which IS the real Max-subscription
# constraint — they tell the user when they're burning quota fast
# enough to risk hitting their 5-hour cap mid-run.
line3=""
if [ -n "$tot_tokens" ] && [[ "$tot_tokens" =~ ^[0-9]+$ ]]; then
  if [ -n "$tpm" ] && [[ "$tpm" =~ ^[0-9.]+$ ]]; then
    tpm_formatted=$(printf '%.0f' "$tpm")
    line3="📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
  else
    line3="📊 $(usage_color)${tot_tokens} tok$(rst)"
  fi
fi

# Line 4: /usage today breakdown — top skill/subagent/MCP by token attribution
# from local session transcripts (~/.claude/projects/**/*.jsonl modified today).
# Mirrors Boris's /usage interactive output: percentages can overlap because a
# turn may invoke multiple tool categories.
line4=""
#
# Skipped in lean mode (F1): this helper aggregates ~/.claude/projects/**/*.jsonl,
# so like ccusage its cost scales with the run's own transcript output — the same
# feedback loop, one layer over. Its 60s cache bounds the rate, not the cost.
USAGE_BREAKDOWN_HELPER="$PROJECT_ROOT/.claude/scripts/usage-breakdown.sh"
if [ "$PWT_LEAN" -eq 0 ] && [ -x "$USAGE_BREAKDOWN_HELPER" ] && [ "$HAS_JQ" -eq 1 ]; then
  ub_json=$("$USAGE_BREAKDOWN_HELPER" 2>/dev/null)
  if [ -n "$ub_json" ] && [ "$ub_json" != "{}" ]; then
    # Build "🎯 Today: Skill /X N% · Agent Y N% · MCP Z N%" segment.
    # Each row pulls the top-1 entry; if no entries, the segment is skipped.
    parts=""
    top_skill=$(echo "$ub_json" | jq -r '.skills[0] | "\(.name) \(.pct)"' 2>/dev/null)
    if [ -n "$top_skill" ] && [ "$top_skill" != "null null" ]; then
      sk_name=$(echo "$top_skill" | awk '{print $1}')
      sk_pct=$(echo "$top_skill" | awk '{print $2}')
      parts="$(C '38;5;117')Skill$(rst) $(C '38;5;215')/${sk_name}$(rst) ${sk_pct}%"
    fi
    top_agent=$(echo "$ub_json" | jq -r '.subagents[0] | "\(.name) \(.pct)"' 2>/dev/null)
    if [ -n "$top_agent" ] && [ "$top_agent" != "null null" ]; then
      ag_name=$(echo "$top_agent" | awk '{print $1}')
      ag_pct=$(echo "$top_agent" | awk '{print $2}')
      [ -n "$parts" ] && parts="$parts $(C '38;5;245')·$(rst) "
      parts="$parts$(C '38;5;117')Agent$(rst) $(C '38;5;215')${ag_name}$(rst) ${ag_pct}%"
    fi
    top_mcp=$(echo "$ub_json" | jq -r '.mcp[0] | "\(.name) \(.pct)"' 2>/dev/null)
    if [ -n "$top_mcp" ] && [ "$top_mcp" != "null null" ]; then
      mc_name=$(echo "$top_mcp" | awk '{print $1}')
      mc_pct=$(echo "$top_mcp" | awk '{print $2}')
      [ -n "$parts" ] && parts="$parts $(C '38;5;245')·$(rst) "
      parts="$parts$(C '38;5;117')MCP$(rst) $(C '38;5;215')${mc_name}$(rst) ${mc_pct}%"
    fi
    [ -n "$parts" ] && line4="🎯 $(C '38;5;117')Today:$(rst) $parts"
  fi
fi

# Print lines
if [ -n "$line2" ]; then
  printf '\n%s' "$line2"
fi
if [ -n "$line3" ]; then
  printf '\n%s' "$line3"
fi
if [ -n "$line4" ]; then
  printf '\n%s' "$line4"
fi
printf '\n'
